import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Camera, FileText, Flame, MessageCircleQuestion, Sparkle, Type, Zap } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { SiteHeader } from "@/components/SiteHeader";
import { SetCard, type SetSummary } from "@/components/SetCard";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "yLearn — AI flashcards from your notes" },
      {
        name: "description",
        content:
          "Snap a textbook page, paste your notes or type a topic. yLearn writes the flashcards, quizzes and summaries for you.",
      },
      { property: "og:title", content: "yLearn — AI flashcards from your notes" },
      {
        property: "og:description",
        content: "Study sets generated by AI for middle and high school students.",
      },
    ],
  }),
  component: Landing,
});

function Landing() {
  const { data: featured } = useQuery({
    queryKey: ["featured-sets"],
    queryFn: async (): Promise<SetSummary[]> => {
      const { data, error } = await supabase
        .from("study_sets")
        .select("id, title, subject, description, author_name, visibility, cards(count)")
        .eq("visibility", "public")
        .order("created_at", { ascending: false })
        .limit(3);
      if (error) throw error;
      return (data ?? []).map((s) => ({
        ...s,
        cardCount: (s.cards as unknown as { count: number }[])?.[0]?.count ?? 0,
      })) as SetSummary[];
    },
  });

  return (
    <div className="min-h-screen">
      <SiteHeader />

      <main>
        <section className="glow-grid px-4 pb-16 pt-14 sm:pt-20">
          <div className="mx-auto max-w-3xl text-center">
            <span className="inline-flex items-center gap-2 rounded-full border border-border bg-card px-3 py-1 text-xs font-medium text-muted-foreground">
              <Sparkle className="h-3.5 w-3.5 text-accent" /> 100% AI-generated study sets
            </span>
            <h1 className="mt-6 text-4xl font-bold leading-[1.05] sm:text-6xl">
              Stop writing flashcards.
              <br />
              <span className="text-primary">Start learning them.</span>
            </h1>
            <p className="mx-auto mt-5 max-w-xl text-base text-muted-foreground sm:text-lg">
              Photograph your textbook page, paste your notes, or just type a topic. yLearn turns it
              into flashcards, a quiz and a summary in seconds — and a tutor who explains anything
              you don't get.
            </p>
            <div className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row">
              <Button asChild size="lg" className="w-full sm:w-auto">
                <Link to="/create">
                  <Zap className="h-4 w-4" /> Generate my first set
                </Link>
              </Button>
              <Button asChild size="lg" variant="secondary" className="w-full sm:w-auto">
                <Link to="/explore">Explore community sets</Link>
              </Button>
            </div>
          </div>

          <div className="mx-auto mt-14 grid max-w-4xl gap-4 sm:grid-cols-3">
            {[
              {
                icon: Camera,
                title: "Snap it",
                body: "Photo of a summary page, textbook spread or your own handwriting.",
              },
              {
                icon: Type,
                title: "Type it",
                body: "\"French Unit 3 Vocab\" is enough. The AI knows what to cover.",
              },
              {
                icon: FileText,
                title: "Paste it",
                body: "Drop in your notes or a PDF and get structured cards back.",
              },
            ].map((f) => (
              <div key={f.title} className="rounded-2xl border border-border bg-card p-5">
                <f.icon className="h-5 w-5 text-accent" />
                <h3 className="mt-3 font-semibold">{f.title}</h3>
                <p className="mt-1 text-sm text-muted-foreground">{f.body}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="border-y border-border bg-card/40 px-4 py-14">
          <div className="mx-auto grid max-w-5xl gap-8 sm:grid-cols-3">
            {[
              {
                icon: Sparkle,
                title: "Flashcards with memory",
                body: "Rate each card Easy, Medium or Hard. yLearn schedules the hard ones to come back sooner.",
              },
              {
                icon: MessageCircleQuestion,
                title: "Quizzes on demand",
                body: "Multiple choice and fill-in-the-blank questions written fresh from your set.",
              },
              {
                icon: Flame,
                title: "Streaks that stick",
                body: "Every study day counts. Watch your streak and cards learned climb.",
              },
            ].map((f) => (
              <div key={f.title}>
                <f.icon className="h-6 w-6 text-primary" />
                <h3 className="mt-3 text-lg font-semibold">{f.title}</h3>
                <p className="mt-1.5 text-sm text-muted-foreground">{f.body}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="px-4 py-14">
          <div className="mx-auto max-w-5xl">
            <div className="flex items-end justify-between gap-4">
              <h2 className="text-2xl font-bold sm:text-3xl">Fresh from the community</h2>
              <Button asChild variant="ghost" size="sm">
                <Link to="/explore">See all</Link>
              </Button>
            </div>
            <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {(featured ?? []).map((set) => (
                <SetCard key={set.id} set={set} />
              ))}
            </div>
          </div>
        </section>
      </main>

      <footer className="border-t border-border px-4 py-8 text-center text-sm text-muted-foreground">
        yLearn — AI study sets for middle and high school.
      </footer>
    </div>
  );
}
